# Generated by Django 5.2 on 2025-05-23 14:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aircraft_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aircraft_types/')),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('range_nautical_miles', models.PositiveIntegerField(help_text='Maximum range in nautical miles')),
                ('speed_knots', models.PositiveIntegerField(help_text='Cruising speed in knots')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4, unique=True)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_private_aviation_friendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('owner', 'Aircraft Owner'), ('agent', 'Booking Agent'), ('admin', 'System Admin')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('year_manufactured', models.PositiveIntegerField()),
                ('base_airport', models.CharField(help_text='ICAO code of home airport', max_length=10)),
                ('current_location', models.CharField(help_text='ICAO code of current location', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Base hourly rate in USD', max_digits=10)),
                ('minimum_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to=settings.AUTH_USER_MODEL)),
                ('interior_images', models.ManyToManyField(blank=True, to='myapplication.aircraftimage')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapplication.aircrafttype')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.PositiveIntegerField(help_text='Altitude in feet')),
                ('heading', models.PositiveIntegerField(help_text='Heading in degrees')),
                ('speed', models.PositiveIntegerField(help_text='Speed in knots')),
                ('source', models.CharField(help_text='Source of tracking data', max_length=50)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='myapplication.aircraft')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='myapplication.aircraft')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_leg', 'Multi-leg')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agent_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='myapplication.aircraft')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('frequent_flyer_programs', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
                ('preferred_aircraft_types', models.ManyToManyField(blank=True, to='myapplication.aircrafttype')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('flight_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('passenger_count', models.PositiveIntegerField()),
                ('leg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sequence', models.PositiveIntegerField()),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='myapplication.airport')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_legs', to='myapplication.booking')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='myapplication.airport')),
            ],
            options={
                'ordering': ['booking', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_date', models.DateField()),
                ('transaction_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='myapplication.booking')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('empty_leg_discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for empty leg flights', max_digits=5)),
                ('peak_season_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for peak season pricing', max_digits=5)),
                ('weekend_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Additional percentage for weekend flights', max_digits=5)),
                ('last_minute_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Additional percentage for bookings made within 24 hours', max_digits=5)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.aircrafttype')),
            ],
        ),
    ]
