# Generated by Django 5.2 on 2025-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0002_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
