# Generated by Django 5.2 on 2025-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0003_passenger_date_of_birth_passenger_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
