# Generated by Django 5.2 on 2025-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0004_passenger_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='order',
            field=models.CharField(blank=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
