# Generated by Django 5.2 on 2025-05-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0005_alter_passenger_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
