# Generated by Django 5.2 on 2025-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0007_aircargorequest_aircraftleasinginquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('passenger_count', models.PositiveIntegerField()),
                ('travel_date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
