# Generated by Django 5.2 on 2025-05-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0008_groupinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(choices=[('Charter Inquiry', 'Charter Inquiry'), ('Membership', 'Membership'), ('Group Booking', 'Group Booking'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
