# Generated by Django 5.2 on 2025-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0010_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='category',
            field=models.CharField(choices=[('helicopter', 'Helicopter'), ('chopper', 'Chopper'), ('jet', 'Jet'), ('drone', 'Drone'), ('propeller', 'Propeller Plane'), ('glider', 'Glider')], default='helicopter', max_length=20),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='price_per_hour_usd',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Hourly lease price in USD', max_digits=10),
            preserve_default=False,
        ),
    ]
