# Generated by Django 5.2 on 2025-06-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0011_aircrafttype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafttype',
            name='category',
            field=models.CharField(choices=[('helicopter', 'Helicopter'), ('chopper', 'Chopper'), ('jet', 'Jet'), ('propeller', 'Propeller Plane'), ('glider', 'Glider')], default='helicopter', max_length=20),
        ),
        migrations.AlterField(
            model_name='aircrafttype',
            name='price_per_hour_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
