# Generated by Django 5.2 on 2025-06-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0012_alter_aircrafttype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftleasinginquiry',
            name='supporting_document_1',
            field=models.FileField(blank=True, null=True, upload_to='aircraft_leasing/documents/'),
        ),
        migrations.AddField(
            model_name='aircraftleasinginquiry',
            name='supporting_document_2',
            field=models.FileField(blank=True, null=True, upload_to='aircraft_leasing/documents/'),
        ),
    ]
