# Generated by Django 5.2 on 2025-06-18 07:56

import myapplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0013_aircraftleasinginquiry_supporting_document_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftleasinginquiry',
            name='inquiry_code',
            field=models.CharField(blank=True, default=myapplication.models.generate_inquiry_code, editable=False, max_length=10, null=True),
        ),
    ]
