# Generated by Django 5.2 on 2025-06-18 08:00

import myapplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0014_aircraftleasinginquiry_inquiry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftleasinginquiry',
            name='inquiry_code',
            field=models.CharField(blank=True, default=myapplication.models.generate_inquiry_code, max_length=10, null=True),
        ),
    ]
