# Generated by Django 5.2 on 2025-06-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0016_alter_aircraftleasinginquiry_inquiry_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_flight_hours', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('nautical_miles', models.PositiveIntegerField(default=0)),
                ('aircraft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='myapplication.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('flight_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('nautical_miles', models.PositiveIntegerField()),
                ('passengers', models.PositiveSmallIntegerField()),
                ('booking_reference', models.CharField(blank=True, max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_history', to='myapplication.aircraft')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='myapplication.aircraft')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Owner Dashboards',
            },
        ),
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapplication.aircraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
