# Generated by Django 5.2 on 2025-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0017_aircraftperformance_flightroute_maintenanceticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinquiry',
            name='departure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groupinquiry',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinquiry',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groupinquiry',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinquiry',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupinquiry',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate Travel'), ('group', 'Group Travel')], max_length=20, null=True),
        ),
    ]
