# Generated by Django 5.2 on 2025-06-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0018_groupinquiry_departure_groupinquiry_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_empty_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stay_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
