from django.core.management.base import BaseCommand
from myapplication.models import Airport

class Command(BaseCommand):
    help = 'Seed the database with major airports in Africa and Europe'

    def handle(self, *args, **options):
        airports = [
            # Africa
            {
                'icao_code': 'HKJK',
                'iata_code': 'NBO',
                'name': 'Jomo Kenyatta International Airport',
                'city': 'Nairobi',
                'country': 'Kenya',
                'latitude': -1.319167,
                'longitude': 36.9275,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'DNMM',
                'iata_code': 'LOS',
                'name': 'Murtala Muhammed International Airport',
                'city': 'Lagos',
                'country': 'Nigeria',
                'latitude': 6.577222,
                'longitude': 3.321111,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'FAOR',
                'iata_code': 'JNB',
                'name': 'O. R. Tambo International Airport',
                'city': 'Johannesburg',
                'country': 'South Africa',
                'latitude': -26.133333,
                'longitude': 28.25,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'HECA',
                'iata_code': 'CAI',
                'name': 'Cairo International Airport',
                'city': 'Cairo',
                'country': 'Egypt',
                'latitude': 30.121944,
                'longitude': 31.405556,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'HAAB',
                'iata_code': 'ADD',
                'name': 'Addis Ababa Bole International Airport',
                'city': 'Addis Ababa',
                'country': 'Ethiopia',
                'latitude': 8.977778,
                'longitude': 38.799444,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'GMMN',
                'iata_code': 'CMN',
                'name': 'Mohammed V International Airport',
                'city': 'Casablanca',
                'country': 'Morocco',
                'latitude': 33.3675,
                'longitude': -7.589722,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'DAAG',
                'iata_code': 'ALG',
                'name': 'Houari Boumediene Airport',
                'city': 'Algiers',
                'country': 'Algeria',
                'latitude': 36.691,
                'longitude': 3.215,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'DFFD',
                'iata_code': 'OUA',
                'name': 'Ouagadougou Airport',
                'city': 'Ouagadougou',
                'country': 'Burkina Faso',
                'latitude': 12.353194,
                'longitude': -1.512417,
                'is_private_aviation_friendly': False,
            },
            {
                'icao_code': 'GABS',
                'iata_code': 'BKO',
                'name': 'Modibo Keita International Airport',
                'city': 'Bamako',
                'country': 'Mali',
                'latitude': 12.5335,
                'longitude': -7.94994,
                'is_private_aviation_friendly': False,
            },
            {
                'icao_code': 'HSSS',
                'iata_code': 'KRT',
                'name': 'Khartoum International Airport',
                'city': 'Khartoum',
                'country': 'Sudan',
                'latitude': 15.5895,
                'longitude': 32.5532,
                'is_private_aviation_friendly': False,
            },
            # Europe
            {
                'icao_code': 'EGLL',
                'iata_code': 'LHR',
                'name': 'London Heathrow Airport',
                'city': 'London',
                'country': 'United Kingdom',
                'latitude': 51.4706,
                'longitude': -0.461941,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'LFPG',
                'iata_code': 'CDG',
                'name': 'Paris Charles de Gaulle Airport',
                'city': 'Paris',
                'country': 'France',
                'latitude': 49.0097,
                'longitude': 2.5479,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'EDDF',
                'iata_code': 'FRA',
                'name': 'Frankfurt am Main Airport',
                'city': 'Frankfurt',
                'country': 'Germany',
                'latitude': 50.0379,
                'longitude': 8.5622,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'EHAM',
                'iata_code': 'AMS',
                'name': 'Amsterdam Airport Schiphol',
                'city': 'Amsterdam',
                'country': 'Netherlands',
                'latitude': 52.3086,
                'longitude': 4.7639,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'LEMD',
                'iata_code': 'MAD',
                'name': 'Adolfo Suárez Madrid–Barajas Airport',
                'city': 'Madrid',
                'country': 'Spain',
                'latitude': 40.472,
                'longitude': -3.5608,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'LIRF',
                'iata_code': 'FCO',
                'name': 'Leonardo da Vinci–Fiumicino Airport',
                'city': 'Rome',
                'country': 'Italy',
                'latitude': 41.8003,
                'longitude': 12.2389,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'LOWW',
                'iata_code': 'VIE',
                'name': 'Vienna International Airport',
                'city': 'Vienna',
                'country': 'Austria',
                'latitude': 48.1103,
                'longitude': 16.5697,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'EKCH',
                'iata_code': 'CPH',
                'name': 'Copenhagen Airport',
                'city': 'Copenhagen',
                'country': 'Denmark',
                'latitude': 55.6181,
                'longitude': 12.6561,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'ESSA',
                'iata_code': 'ARN',
                'name': 'Stockholm Arlanda Airport',
                'city': 'Stockholm',
                'country': 'Sweden',
                'latitude': 59.6519,
                'longitude': 17.9186,
                'is_private_aviation_friendly': True,
            },
            {
                'icao_code': 'EFHK',
                'iata_code': 'HEL',
                'name': 'Helsinki-Vantaa Airport',
                'city': 'Helsinki',
                'country': 'Finland',
                'latitude': 60.3172,
                'longitude': 24.9633,
                'is_private_aviation_friendly': True,
            },
        ]

        for airport_data in airports:
            airport, created = Airport.objects.get_or_create(
                icao_code=airport_data['icao_code'],
                defaults=airport_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"Added airport: {airport.name} ({airport.icao_code})"))
            else:
                self.stdout.write(self.style.WARNING(f"Airport already exists: {airport.name} ({airport.icao_code})"))
